language: go

go:
  - 1.7
  - 1.8
  - master

before_install:
  - go get github.com/mattn/goveralls

script:
  #- go test -v $(go list ./... | grep -v /vendor/)
  - make test

after_success:
  - make COVERALLS=true coveralls
  - make TRAVIS="${TRAVIS}" TRAVIS_BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}" TRAVIS_BUILD_ID="${TRAVIS_BUILD_ID}" release