language: go

go:
  - 1.7
  - 1.8
  - master

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/onsi/ginkgo/ginkgo

script:
  - echo "${GOPATH}"
  - ls -al "${GOPATH}/bin"
  - make test

after_success:
  - make COVERALLS=true coveralls
  - make RELEASE=${RELEASE} GH_TOKEN=${GH_TOKEN} TRAVIS="${TRAVIS}" TRAVIS_BUILD_NUMBER="${TRAVIS_BUILD_NUMBER}" TRAVIS_BUILD_ID="${TRAVIS_BUILD_ID}" TRAVIS_JOB_NUMBER="${TRAVIS_JOB_NUMBER}" release