language: go

go:
  - 1.7
  - 1.8
  - master

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v $(go list ./... | grep -v /vendor/)

after_success:
  - COVERALLS=true ./test-coverage.sh