language: go

go:
  - 1.7
  - 1.8
  - master

env:
  - MONGODB_PORT_27017_TCP_ADDR=127.0.0.1

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v $(go list ./... | grep -v /vendor/)

after_success:
  - COVERALLS=true ./test-coverage.sh